language: elixir

elixir:
  - 1.2.2
otp_release:
  - 18.2.1

addons:
  postgresql: "9.4"

services:
  - postgresql

cache:
  directories:
    - _build
    - deps

before_install:
   - cp config/mailer.example.exs config/mailer.exs

before_script:
  - psql -c "CREATE USER \"doom\" WITH SUPERUSER CREATEDB PASSWORD 'doom';" -U postgres
  - mix local.hex --force
  - mix local.rebar
  - mix deps.get --only test
  - MIX_ENV=test mix ecto.reset

script:
  - mix test
